// expectedObjectsViews.js
window.expectedTealiumViewObjects = [
  {
    event: "TealiumView",
    currency: /^[A-Z]{3}$/, // e.g., GBP, EUR
    funnel_name: "Trains",
    page_category: /^SearchResults$/, // strict category
    isLoggedIn: /^(true|false)$/,
    customer_hashedemail: /^[a-f0-9]{64}$/,
    membershipID: /^\d{17}$/,
    loyaltyTier: /^(Classique|Carte Blanche|Etoile|Silver|Gold|null)$/,
    pointsToSpend: /^\d+$/,
    pointsToUpgrade: /^\d+|null$/,
    customer_is_admin: /^(true|false|null)$/,
    businessID: /^(null|[\w-]*)$/,
    subscriptionDuration: /^(null|\d+)$/,
    subscriptionRemainingDuration: /^(null|\d+)$/,
    pointsOrRegular: /^(regular booking|points booking)$/,
    numberOfResults: /^\d+$/,
    numberOfTrainsAvailable: /^\d+$/,
    sOutboundLowestFare: /^\d+$/,
    sInboundLowestFare: /^(\d+|null)$/,
    numberOfSalesTagsAvailable: /^\d+$/,
    directOrConnection: /^(direct|connection|mixed)$/,
    sJourneyType: /^(One way|Return)$/,
    sFromCode: /^\d{7}$/,
    sFromName: /^.+$/,
    sToCode: /^\d{7}$/,
    sToName: /^.+$/,
    sDateOutbound: /^\d{4}-\d{2}-\d{2}$/,
    sDateInbound: /^(\d{4}-\d{2}-\d{2}|null)$/,
    sTravelDuration: /^\d+$/,
    sTravelHorizon: /^\d+$/,
    sPaxAdult: /^\d+$/,
    sPaxChildren: /^\d+$/,
    sPaxYouth: /^\d+$/,
    sPaxInfants: /^\d+$/,
    sPaxSenior: /^\d+$/,
    sPaxTotal: /^\d+$/,
    basket_value: /^\d+$/,
    basket_value_inpoints: /^\d+$/,
    ecommerce_action: "product impressions",
    products_count: /^\d+$/,
    product_name: [/^\d{7} - \d{7}(:adult)?$/], // as array
    product_id: [/^\d{7} - \d{7}$/],
    product_quantity: [/^\d+$/],
    product_status: [/^(available|not available)$/],
    product_price: [/^\d+\.\d{2}$/],
    product_price_inpoints: [/^\d+$/],
    product_brand: [/^[A-Z]{2}$/], // e.g., ES, ER
    product_category: ["trains"],
    product_variant: ["outbound"],
    product_departure_date: [/^\d{4}-\d{2}-\d{2}$/],
    product_return_date: [], // optional
    product_train_class: [/^Eurostar (Standard|Plus|Premier)$/],
    product_train_route: [/^(london route|continent route)$/],
    product_train_origin_stationcode: [/^\d{7}$/],
    product_train_destination_stationcode: [/^\d{7}$/],
    product_train_number: [/^\d{4}$/],
    product_train_fbccode: [/^.*$/], // some may be null
    product_train_departuretime: [/^\d{2}:\d{2}$/],
    product_train_arrivaltime: [/^\d{2}:\d{2}$/],
    product_train_numberofconnections: [/^\d+$/],
    product_train_connectionoperator: [/^(null|Eurostar|SNCF)?$/],
    product_train_tickettype: [/^(ESTAR_PUB_(STD|PLUS|PREM)|SNCF1SF|RED_ESTAR_PUB_PLUS|null)$/],
    product_train_passenger_type: ["adult"],
    product_train_sale_tag: [/^(lowest fare|null)?$/],
    product_travel_date: [/^\d{4}-\d{2}-\d{2}$/],
    product_train_fare_name: [/^(through fare|null)?$/],
    product_train_fare_type: [/^(ES_ER|ER_SN|null)?$/],
    product_total_journey_length: [/^\d+$/],
    product_train_journey_length: [/^\d+$/],
    page_name: "SearchResults"
  },
  {
	app_platform: "ReactJS",
	app_name: "TravelExtras",
	market: "uk",
	language: "en",
	currency: /^(GBP|EUR|USD)$/,
	event: "TealiumView",
	sFromCode: /^\d{7}$/,
	sFromName: /^.+$/,
	sToCode: /^\d{7}$/,
	sToName: /^.+$/,
	sJourneyType: /^(One way|Return)$/,
	directOrConnection: /^(direct|connection|mixed)$/,
	specialBooking: "",
	sDateOutbound: /^\d{4}-\d{2}-\d{2}$/,
	sTravelHorizon: /^\d+$/,
	sPaxTotal: /^\d+$/,
	sPaxSenior: /^\d+$/,
	sPaxAdult: /^\d+$/,
	sPaxYouth: /^\d+$/,
	sPaxChildren: /^\d+$/,
	sPaxInfants: /^\d+$/,
	sPaxCompanion: /^\d+$/,
	pointsOrRegular:/^(regular booking|points booking)$/,
	basket_value: /^\d+$/,
	basket_value_inpoints: /^\d+$/,
	sTrainNumberOutbound: "9080",
	sOutboundTime: "06:01",
	sClassOutbound: "Eurostar Plus",
	sTrainTarriffOutbound: "H19PSXASBGN",
	funnel_name: "Trains",
	page_name: "TravelExtras"
}
];
